import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import '../docs/javascripts/effect-toolkit-engine.js';
import {__test as auth} from '../cloudflare/wiki-auth/_worker.js';
const E=globalThis.SFHEffectToolkit,c=JSON.parse(await readFile('docs/assets/effect-toolkit.json','utf8'));
assert.equal(auth.isPublicPath('/assets/effect-toolkit.json'),false,'code catalog requires authentication');
assert.equal(auth.isPublicPath('/tools/effect-toolkit/'),false,'guide requires authentication');
const row=(f,t)=>({spec_id:'test-spec',status:'draft',target_kind:f.kind,target_id:t.id,field_id:f.id,value:t.current,notion_url:'',intent:'현행 효과를 명시',acceptance:'대상에 지정한 효과가 동작하고 해제 시 원복',owner_status:'pending',source_fingerprint:c.fingerprint});
let count=0;
for(const f of c.fields)for(const t of f.targets){const r=row(f,t),p=E.compile([r],c);assert.equal(p.game_applied,false);assert.equal(p.changes[0].result,'review_required');assert.deepEqual(E.parseCSV(E.csv([r])),[Object.fromEntries(Object.entries(r).map(([k,v])=>[k,String(v)]))]);count++;}
const f=c.fields.find(f=>f.id==='skill.energy_cost'),r=row(f,f.targets[0]);
for(const value of ['',null,undefined,true,'NaN','Infinity',-1,1001])assert.throws(()=>E.compile([{...r,value}],c));
assert.equal(E.compile([{...r,value:0}],c).changes[0].value,0);
for(const patch of [{field_id:'missing'},{target_id:'missing'},{source_fingerprint:'old'},{intent:''},{acceptance:''},{status:'implemented'},{owner_status:'yes'},{notion_url:'https://notion.site.evil.test/a'},{notion_url:'javascript:alert(1)'},{notion_url:'https://user@notion.site/a'},{status:'confirmed'},{unknown:'x'}])assert.throws(()=>E.compile([{...r,...patch}],c));
assert.throws(()=>E.compile([r,r],c));
const confirmed={...r,status:'confirmed',notion_url:'https://example.notion.site/source'};
assert.equal(E.compile([confirmed],c).changes[0].result,'review_required');
assert.equal(E.compile([{...confirmed,owner_status:'approved'}],c).changes[0].result,'reviewed_change_plan');
assert.equal(E.compile([{...r,field_id:'custom_effect',value:'명중 시 연쇄 전기 / 최대 3명 / 1회 / 중첩 없음'}],c).requests[0].result,'implementation_required');
const exotic={...r,intent:'쉼표, 따옴표 "검수"\n다음 줄'};
assert.equal(E.parseCSV(E.csv([exotic]))[0].intent,exotic.intent);
const header=E.columns.join(',')+'\n'+['명세 고유 ID',...Array(10).fill('설명')].join(',')+'\n';
assert.equal(E.parseCSV(header+E.csv([r]).split('\n').slice(1).join('\n')).length,1);
assert.throws(()=>E.parseCSV('bad,header\n'));
assert.throws(()=>E.parseCSV(E.columns.join(',')+'\n"unterminated'));
assert.throws(()=>E.parseCSV(E.columns.join(',')+'\n"abc"x'));
const innate=c.fields.find(f=>f.id==='weapon.innate_effect_kind');
const single=innate.targets.find(t=>t.current==='single_target');
const w={...row(innate,single),value:'electric_area'};
assert.throws(()=>E.compile([w],c));
assert.equal(E.compile([w,{...w,field_id:'weapon.innate_effect_radius',value:144}],c).changes.length,2);
for(const t of innate.targets)assert.equal(t.bindings.length,2,'Identity includes runtime and CSV');
assert.match(E.markdown([r],c),/자동 적용되지 않습니다/);
console.log(`EFFECT_TOOLKIT_OK ${count} bindings; bounds, source, approval, CSV, custom and composed rules`);
