extends SceneTree

var failures := PackedStringArray()

func _init() -> void:
	_run.call_deferred()

func check(ok: bool, note: String) -> void:
	if not ok: failures.append(note)

func _run() -> void:
	var player = load("res://game/features/player/player.tscn").instantiate()
	root.add_child(player)
	player.set_physics_process(false)
	var feedback = player.get_node("MovementFeedback")
	feedback.set_physics_process(false)
	var camera: Camera2D = player.get_node("Camera2D")
	camera.offset = Vector2(3, 2)
	for i in 45: feedback.advance_feedback(Vector2(660, 0), 280.0, 1.0/60.0, true, Vector2(i*11, 0))
	check(camera.zoom.x < 0.94 and camera.zoom.x >= 0.92, "dash zoom visible and bounded")
	check(camera.position.x > 65.0, "direction lead strengthened")
	check(camera.offset == Vector2(3, 2), "movement never overwrites hit offset")
	for i in 120: feedback.advance_feedback(Vector2.ZERO, 280.0, 1.0/60.0, false, Vector2.ZERO)
	check(camera.zoom.distance_to(Vector2.ONE) < 0.001 and camera.position.length() < 0.01, "stop restores framing")
	feedback.set_feedback_enabled(false)
	check(camera.zoom == Vector2.ONE, "disable restores zoom exactly")
	var weapon = load("res://game/features/weapons/auto_weapon.tscn").instantiate()
	root.add_child(weapon)
	weapon.set_process(false)
	var fx = weapon.get_node("ShotFX")
	check(not fx.is_processing() and fx.flashes.is_empty(), "idle flash has no processing")
	for i in 100: weapon.projectile_fired.emit(Vector2(i,0), Vector2.RIGHT, Color.CYAN)
	check(fx.total_events == 100 and fx.flashes.size() == 16, "signal connected and burst budget bounded")
	fx._process(fx.flash_lifetime + 0.01)
	check(not fx.is_processing() and fx.flashes.is_empty(), "flashes fully drain")
	var profile = load("res://game/features/combat_skills/effects/profiles/magnetic_electric.tres").duplicate(true)
	profile.lifetime_seconds = 5.0
	var electric = load("res://game/features/combat_skills/effects/electric_arc_effect.gd").new()
	root.add_child(electric)
	electric.configure_radial(230.0, profile, player)
	electric.set_process(false)
	electric._process(4.0)
	check(electric.self_modulate.a > 0.99, "active field remains readable at 80 percent lifetime")
	electric._process(0.9)
	check(electric.self_modulate.a > 0.0 and electric.self_modulate.a < 0.5, "short final fade")
	check(electric.geometry_rebuild_count <= 3 and electric.maximum_radius == 230.0, "long delta bounded geometry and fixed range")
	var effect = load("res://game/features/combat_skills/effects/speed_boost_skill_effect.gd").new()
	effect.electric_profile = load("res://game/features/combat_skills/effects/profiles/speed_electric.tres")
	var outcome: Dictionary = effect.activate(player, {&"mechanic_override":{&"duration_multiplier":2.0}})
	check(outcome.success, "speed effect activation")
	var owner = player.get_node("CombatSkillSpeedBoost")
	check(owner.get_child_count() == 1 and owner.get_child(0).profile.lifetime_seconds == 8.0, "aura follows resolved buff lifetime")
	var visual_ref = weakref(owner.get_child(0))
	owner.free()
	check(visual_ref.get_ref() == null, "cancel removes speed aura")
	check(Engine.time_scale == 1.0, "no global hit stop")
	weapon.free()
	electric.free()
	player.free()
	for failure in failures: printerr(failure)
	print("COMBAT_FX_OK camera_bound stop_restore offset_owner shot_signal burst_cap idle active_visibility lifespan_cancel" if failures.is_empty() else "COMBAT_FX_FAILED")
	quit(0 if failures.is_empty() else 1)
